# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-21 19:27
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalBoundary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326)),
                ('region', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'Regional_Boundary',
                'managed': False,
            },
        ),
    ]
