# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-21 19:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='incidentReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(blank=True, max_length=2500, null=True)),
                ('image', models.ImageField(null=True, upload_to='galamsey/pic/')),
                ('voice', models.FileField(upload_to='galamsey/audio/')),
                ('gps_coordinates_lat', models.FloatField(default=0)),
                ('gps_coordinates_lng', models.FloatField(default=0)),
                ('gps_coordinates_geom', django.contrib.gis.db.models.fields.PointField(blank=True, editable=False, null=True, srid=4326)),
            ],
        ),
    ]
