# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-22 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey', '0004_auto_20190722_0519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentreports',
            old_name='gps_coordinates_geom',
            new_name='geom',
        ),
        migrations.RenameField(
            model_name='incidentreports',
            old_name='gps_coordinates_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='incidentreports',
            old_name='gps_coordinates_lng',
            new_name='lng',
        ),
    ]
