# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-22 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey', '0006_auto_20190722_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentreports',
            name='image',
            field=models.ImageField(null=True, upload_to='galamsey/pic/'),
        ),
        migrations.AlterField(
            model_name='incidentreports',
            name='voice',
            field=models.FileField(upload_to='galamsey/audio/'),
        ),
    ]
