# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-26 04:39
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey', '0007_auto_20190722_0756'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_date', models.CharField(blank=True, max_length=200, null=True)),
                ('delete_field', models.CharField(blank=True, max_length=10, null=True)),
                ('district_name', models.CharField(blank=True, max_length=50, null=True)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
                ('region', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'District',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='incidentreports',
            name='status',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
    ]
