# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-02 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galamsey', '0010_charcoalreports_fcm_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='charcoalReports',
        ),
    ]
