# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-17 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusid', models.CharField(db_column='StatusID', max_length=10)),
                ('status_description', models.CharField(blank=True, db_column='Status_Description', max_length=40, null=True)),
                ('status_code', models.TextField(blank=True, db_column='Status_Code', null=True)),
            ],
            options={
                'db_table': 'Allocation_Status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('binid', models.CharField(db_column='BinID', max_length=15)),
                ('bin_code', models.CharField(blank=True, db_column='Bin_Code', max_length=15, null=True)),
                ('bin_name', models.CharField(blank=True, db_column='Bin_Name', max_length=30, null=True)),
                ('allocation_status', models.CharField(blank=True, db_column='Allocation_Status', max_length=15, null=True)),
                ('date_created', models.DateField(blank=True, db_column='Date_Created', null=True)),
                ('bin_colour', models.CharField(blank=True, db_column='Bin_Colour', max_length=10, null=True)),
                ('bin_size', models.CharField(blank=True, db_column='Bin_Size', max_length=10, null=True)),
                ('bin_type', models.CharField(blank=True, db_column='Bin_Type', max_length=10, null=True)),
                ('bin_quantity', models.CharField(blank=True, db_column='Bin_Quantity', max_length=10, null=True)),
                ('bin_unit_price', models.CharField(blank=True, db_column='Bin_Unit_Price', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Bin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BinsMovement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(db_column='Bin_Code', max_length=15)),
                ('bin_name', models.CharField(blank=True, db_column='Bin_Name', max_length=20, null=True)),
                ('bin_quantity_issued', models.CharField(blank=True, db_column='Bin_Quantity_Issued', max_length=10, null=True)),
                ('bin_unit_price', models.CharField(blank=True, db_column='Bin_Unit_Price', max_length=10, null=True)),
                ('client_issued_to', models.CharField(blank=True, db_column='Client_Issued_To', max_length=30, null=True)),
                ('date_issued', models.DateField(blank=True, db_column='Date_Issued', null=True)),
                ('bin_type', models.CharField(blank=True, db_column='Bin_Type', max_length=15, null=True)),
                ('issuing_company', models.CharField(blank=True, db_column='Issuing_Company', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Bins_Movement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BinsReceipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_code', models.CharField(blank=True, db_column='Bin_Code', max_length=15, null=True)),
                ('bin_name', models.CharField(blank=True, db_column='Bin_Name', max_length=30, null=True)),
                ('bin_quanitity_received', models.CharField(blank=True, db_column='Bin_Quanitity_Received', max_length=10, null=True)),
                ('receiving_company', models.CharField(blank=True, db_column='Receiving_Company', max_length=50, null=True)),
                ('date_received', models.DateField(blank=True, db_column='Date_Received', null=True)),
            ],
            options={
                'db_table': 'Bins_Receipt',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BinStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_statusid', models.CharField(db_column='Bin_StatusID', max_length=15)),
                ('bin_status_name', models.CharField(blank=True, db_column='Bin_Status_Name', max_length=15, null=True)),
                ('bin_status_code', models.CharField(blank=True, db_column='Bin_Status_Code', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Bin_Status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BinType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin_typeid', models.CharField(db_column='Bin_TypeID', max_length=15)),
                ('bin_type_code', models.CharField(blank=True, db_column='Bin_Type_Code', max_length=15, null=True)),
                ('bin_type_name', models.CharField(blank=True, db_column='Bin_Type_Name', max_length=20, null=True)),
            ],
            options={
                'db_table': 'Bin_Type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientBinAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_code', models.CharField(db_column='Client_Code', max_length=10)),
                ('bin_number', models.CharField(blank=True, db_column='Bin_Number', max_length=15, null=True)),
                ('date_of_allocation', models.DateField(blank=True, db_column='Date_Of_Allocation', null=True)),
            ],
            options={
                'db_table': 'Client_Bin_Allocation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClientRewards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientid', models.CharField(db_column='ClientID', max_length=10)),
                ('seg_code', models.CharField(blank=True, db_column='Seg_Code', max_length=15, null=True)),
                ('point_earned', models.CharField(blank=True, db_column='Point_Earned', max_length=10, null=True)),
                ('date', models.DateField(blank=True, db_column='Date', null=True)),
            ],
            options={
                'db_table': 'Client_Rewards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('house_address', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('collectors', models.IntegerField(blank=True, null=True)),
                ('bin', models.CharField(blank=True, max_length=200, null=True)),
                ('bin_status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Clients',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectorid', models.CharField(db_column='CollectorID', max_length=15)),
                ('collector_code', models.CharField(blank=True, db_column='Collector_Code', max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, db_column='First_Name', max_length=15, null=True)),
                ('middle_name', models.CharField(blank=True, db_column='Middle_Name', max_length=15, null=True)),
                ('last_name', models.CharField(blank=True, db_column='Last_Name', max_length=20, null=True)),
                ('district_of_operation', models.CharField(blank=True, db_column='District_Of_Operation', max_length=20, null=True)),
                ('submetro_of_operation', models.CharField(blank=True, db_column='Submetro_Of_Operation', max_length=25, null=True)),
                ('area_of_operation', models.CharField(blank=True, db_column='Area_Of_Operation', max_length=25, null=True)),
                ('company', models.CharField(blank=True, db_column='Company', max_length=50, null=True)),
                ('date_created', models.DateField(blank=True, db_column='Date_Created', null=True)),
                ('target', models.CharField(blank=True, db_column='Target', max_length=40, null=True)),
            ],
            options={
                'db_table': 'Collector',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=500, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('email_address', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('area_of_operation', models.CharField(blank=True, max_length=10, null=True)),
                ('date_of_register', models.DateTimeField(blank=True, null=True)),
                ('district_operation', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'Company',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('bin_no', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'Complaints',
                'managed': True,
            },
        ),
    ]
