# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-31 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_report_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='charcoalReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(blank=True, max_length=100, null=True)),
                ('report', models.CharField(blank=True, max_length=100, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img')),
                ('system_date', models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
