# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-02 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_charcoalreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charcoalreport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='charcoal/img'),
        ),
    ]
