# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-02 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charcoal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='incidentReports',
        ),
    ]
